---
- name: Provision Infra for phonebook Application
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    aws_region: "us-east-1"
    ami_id: 'ami-02e98f78'
    ansible_python_interpreter: '/Users/vikasa/personal/ansible-cookbook/bin/python'
  vars_files:
      - "phonebook_secret.yml"
  tasks:
    - name: Create EC2 Security Group for RDS
      ec2_group:
        name: phonebook_sg
        description: Scurity group for RDS instance
        region: "{{ aws_region }}"
        aws_secret_key: "{{ secret_key }}"
        aws_access_key: "{{ access_key }}"
        rules:
          - proto: tcp
            from_port: 3306
            to_port: 3306
            group_name: phonebook_sg
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: phonebook_sg

    - name: Create RDS Instance
      rds:
          aws_access_key: "{{ access_key }}"
          aws_secret_key: "{{ secret_key }}"
          region: "{{ aws_region }}"
          command: create
          instance_name: phonebook-db01
          db_engine: MySQL
          size: 10
          instance_type: db.t2.micro
          username: cookbook_admin
          password: "{{ rds_admin_pass }}"
          vpc_security_groups: "{{ phonebook_sg.group_id }}"
          multi_zone: no
          wait: true
          wait_timeout: 1000
          backup_retention: 7
          tags:
              Enviornment: cookbook-prod
              Application: cookbook-test
      register: rds_result

    - name: display rds result
      debug: msg={{rds_result}}

    - name: Create phonebook instance
      ec2:
        key_name: my_first_key
        instance_type: "t2.micro"
        image: "{{ ami_id }}"
        wait: yes
        group: phonebook_sg
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ aws_region }}"
        count_tag:
          Name: phonebook01
        exact_count: 1
        instance_tags:
          Name: phonebook01
      register: ec2_public_instance

    - name: debug ec2_public_instance
      debug: msg={{ec2_public_instance}}

    - name: Add hosts to phonebook group
      add_host:
          groups: phonebook
          name: "{{ec2_public_instance.tagged_instances.0.public_dns_name}}"
          ansible_user: centos

    - name: Add hosts to phonebookDB group
      add_host:
          groups: phonebook_db
          name: "{{rds_result.instance.endpoint}}"


- name: Provision phonebook application
  hosts: phonebook
  vars_files:
      - "phonebook_secret.yml"
  roles:
      - phonebook

